live_config_reload = true

# custom them that attempts to mirror iTerm's tango_dark theme
import = [
    "~/.config/alacritty/tango_dark_iterm.toml"
]
[colors]
draw_bold_text_with_bright_colors = true

[window]
padding.x = 5
padding.y = 5
resize_increments = true

# make default size larger
[window.dimensions]
columns = 120
lines = 40

[font]
size = 15.0

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval=500
blink_timeout=0
unfocused_hollow=true

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

# uncomment for Windows
# [terminal]
# shell = { program = "wsl.exe", args = ["~"] }
